# Generated by Django 4.0.1 on 2022-02-17 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DbConnectionInfo',
            fields=[
                ('db_name', models.CharField(max_length=40)),
                ('tbl_name', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('connection_info', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='MetaDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_value', models.CharField(max_length=40)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('tbl_name', models.ForeignKey(max_length=40, on_delete=django.db.models.deletion.CASCADE, to='apps.dbconnectioninfo')),
            ],
        ),
    ]
