# Generated by Django 4.0.1 on 2022-02-17 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_dbconnectioninfo_metadetails_delete_metadetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MetaDetail',
        ),
    ]
